"""Design constants for the bolt-aligned planar leg-wheel example."""

from __future__ import annotations

import math


# This example intentionally drops the hip-abduction package for now.  The model
# is one planar leg module like the reference sketch: one body-fixed thigh
# actuator drives the upper link, a second body-fixed coaxial knee-drive actuator
# drives a crank/pushrod, and a third hub actuator drives the wheel.

ROOT_AXIS = (0.0, 0.0, 0.0)
KNEE_AXIS = (42.0, -126.0, 0.0)
WHEEL_AXIS = (-78.0, -220.0, 0.0)
KNEE_PIVOT_Z = 7.4
KNEE_DRIVE_OUTPUT_Z = 46.0
ROD_PIN_AXIS_Z = 53.2

THIGH_VECTOR_X = KNEE_AXIS[0] - ROOT_AXIS[0]
THIGH_VECTOR_Y = KNEE_AXIS[1] - ROOT_AXIS[1]
THIGH_LENGTH = math.hypot(THIGH_VECTOR_X, THIGH_VECTOR_Y)
THIGH_UNIT_X = THIGH_VECTOR_X / THIGH_LENGTH
THIGH_UNIT_Y = THIGH_VECTOR_Y / THIGH_LENGTH
THIGH_NORMAL_X = -THIGH_UNIT_Y
THIGH_NORMAL_Y = THIGH_UNIT_X

SHANK_VECTOR_X = WHEEL_AXIS[0] - KNEE_AXIS[0]
SHANK_VECTOR_Y = WHEEL_AXIS[1] - KNEE_AXIS[1]
SHANK_LENGTH = math.hypot(SHANK_VECTOR_X, SHANK_VECTOR_Y)
SHANK_UNIT_X = SHANK_VECTOR_X / SHANK_LENGTH
SHANK_UNIT_Y = SHANK_VECTOR_Y / SHANK_LENGTH
SHANK_NORMAL_X = -SHANK_UNIT_Y
SHANK_NORMAL_Y = SHANK_UNIT_X

REMOTE_CRANK_LENGTH = 46.0
DISTAL_CRANK_LENGTH = REMOTE_CRANK_LENGTH
KNEE_DRIVE_AXIS = (
    ROOT_AXIS[0],
    ROOT_AXIS[1],
    KNEE_DRIVE_OUTPUT_Z,
)
PROXIMAL_PUSHROD_PIN = (
    ROOT_AXIS[0] + THIGH_NORMAL_X * REMOTE_CRANK_LENGTH,
    ROOT_AXIS[1] + THIGH_NORMAL_Y * REMOTE_CRANK_LENGTH,
    0.0,
)
DISTAL_PUSHROD_PIN = (
    KNEE_AXIS[0] + THIGH_NORMAL_X * DISTAL_CRANK_LENGTH,
    KNEE_AXIS[1] + THIGH_NORMAL_Y * DISTAL_CRANK_LENGTH,
    0.0,
)

ACTUATOR_OUTPUT_CONNECTOR_Z = 15.0
MOTOR_CAN_RADIUS = 25.0
MOTOR_CAN_HEIGHT = 10.0
MOTOR_CAN_INPUT_FACE_CLEARANCE = 3.2

# Mating interfaces copied from Example 16.  The link-side clearance holes are a
# little larger than the actuator holes so the printed/laser-cut plate can be
# assembled without pretending the screw fits with zero manufacturing clearance.
ACTUATOR_CASE_OUTER_RADIUS = 29.4
OUTPUT_FLANGE_OUTER_RADIUS = 20.35
OUTPUT_FLANGE_REGISTER_INNER_RADIUS = 11.0
OUTPUT_FLANGE_REGISTER_OUTER_RADIUS = 17.5
OUTPUT_FLANGE_BOLT_CIRCLE_RADIUS = 15.0
OUTPUT_FLANGE_BOLT_CLEARANCE_RADIUS = 1.25
OUTPUT_FLANGE_BOLT_COUNTERBORE_RADIUS = 2.05
OUTPUT_FLANGE_BOLT_COUNT = 6
OUTPUT_FLANGE_BOLT_ANGLES_DEGREES = (-18.0, 18.0, 102.0, 138.0, 222.0, 258.0)

HOUSING_MOUNT_BOLT_CIRCLE_RADIUS = 26.4
HOUSING_MOUNT_BOLT_CLEARANCE_RADIUS = 1.8
HOUSING_MOUNT_COUNTERBORE_RADIUS = 3.1
HOUSING_MOUNT_BOLT_COUNT = 12
HOUSING_MOUNT_BOLT_ANGLES_DEGREES = (
    27.0,
    45.0,
    63.0,
    117.0,
    135.0,
    153.0,
    207.0,
    225.0,
    243.0,
    297.0,
    315.0,
    333.0,
)

PIN_CLEARANCE_RADIUS = 3.2
ROD_PIN_CLEARANCE_RADIUS = 2.2
FASTENER_CLEARANCE_RADIUS = 1.7
LIGHTENING_CORNER_RADIUS = 4.0

UPPER_LINK_Z = 2.8
UPPER_LINK_THICKNESS = 5.0
UPPER_LINK_ROOT_RADIUS = 30.5
UPPER_LINK_KNEE_RADIUS = 17.0
UPPER_LINK_WEB_WIDTH = 28.0
UPPER_LINK_WINDOW_LENGTH = 28.0
UPPER_LINK_WINDOW_WIDTH = 14.0

KNEE_BEARING_OUTER_RADIUS = 14.0
KNEE_BEARING_BORE_RADIUS = 6.0
KNEE_BEARING_BOLT_CIRCLE_RADIUS = 10.5
KNEE_BEARING_BOLT_COUNT = 10

SHANK_LINK_Z = 12.4
SHANK_LINK_THICKNESS = 5.0
SHANK_KNEE_RADIUS = 18.0
SHANK_WHEEL_RADIUS = 31.5
SHANK_WEB_WIDTH = 24.0
SHANK_WINDOW_LENGTH = 25.0
SHANK_WINDOW_WIDTH = 12.0

REMOTE_CRANK_Z = 50.4
REMOTE_CRANK_THICKNESS = 4.0
REMOTE_CRANK_WIDTH = 12.0
DISTAL_CRANK_Z = 50.4
DISTAL_CRANK_THICKNESS = 4.0
DISTAL_CRANK_WIDTH = 12.0
PUSHROD_Z = 56.5
PUSHROD_THICKNESS = 3.6
PUSHROD_WIDTH = 9.0

WHEEL_TIRE_RADIUS = 48.0
WHEEL_TIRE_WIDTH = 18.0
WHEEL_TIRE_BORE_RADIUS = 34.0
WHEEL_HUB_PLATE_RADIUS = 21.0
WHEEL_HUB_PLATE_THICKNESS = 4.0
WHEEL_SPOKE_WIDTH = 5.5
WHEEL_SPOKE_COUNT = 8

BODY_STANDOFF_Z = -45.0
BODY_STANDOFF_THICKNESS = 5.0
KNEE_STACK_CLAMP_Z = 47.0
KNEE_STACK_CLAMP_THICKNESS = 2.0
