"""Design constants for the bolt-aligned planar leg-wheel example."""

from __future__ import annotations

import math

from actuator import (
    ACTUATOR_CASE_CLAMP_Z,
    ACTUATOR_OUTPUT_FACE_Z,
    ACTUATOR_PACKAGE_RADIUS,
    OUTPUT_BOLT_ANGLES_DEGREES,
    OUTPUT_BOLT_CIRCLE_RADIUS,
    OUTPUT_BOLT_COUNT,
    OUTPUT_TAP_RADIUS,
    OUTPUT_REGISTER_HEIGHT,
    OUTPUT_REGISTER_RADIUS,
)


# This example intentionally drops the hip-abduction package for now.  The model
# is one planar leg module like the reference sketch: one body-fixed thigh
# actuator drives the upper link, a second body-fixed coaxial knee-drive actuator
# drives a crank/pushrod, and a third hub actuator drives the wheel.

ROOT_AXIS = (0.0, 0.0, 0.0)
KNEE_AXIS = (42.0, -126.0, 0.0)
WHEEL_AXIS = (-78.0, -220.0, 0.0)
KNEE_PIVOT_Z = 6.5
# The knee-drive actuator is mirrored about its unchanged split-clamp plane, so
# its output flange and red crank sit on the side opposite the actuator body.
KNEE_DRIVE_OUTPUT_Z = 85.6
ROD_PIN_AXIS_Z = 85.95

THIGH_VECTOR_X = KNEE_AXIS[0] - ROOT_AXIS[0]
THIGH_VECTOR_Y = KNEE_AXIS[1] - ROOT_AXIS[1]
THIGH_LENGTH = math.hypot(THIGH_VECTOR_X, THIGH_VECTOR_Y)
THIGH_UNIT_X = THIGH_VECTOR_X / THIGH_LENGTH
THIGH_UNIT_Y = THIGH_VECTOR_Y / THIGH_LENGTH
THIGH_NORMAL_X = -THIGH_UNIT_Y
THIGH_NORMAL_Y = THIGH_UNIT_X

SHANK_VECTOR_X = WHEEL_AXIS[0] - KNEE_AXIS[0]
SHANK_VECTOR_Y = WHEEL_AXIS[1] - KNEE_AXIS[1]
SHANK_LENGTH = math.hypot(SHANK_VECTOR_X, SHANK_VECTOR_Y)
SHANK_UNIT_X = SHANK_VECTOR_X / SHANK_LENGTH
SHANK_UNIT_Y = SHANK_VECTOR_Y / SHANK_LENGTH
SHANK_NORMAL_X = -SHANK_UNIT_Y
SHANK_NORMAL_Y = SHANK_UNIT_X

REMOTE_CRANK_LENGTH = 46.0
DISTAL_CRANK_LENGTH = REMOTE_CRANK_LENGTH
KNEE_DRIVE_AXIS = (
    ROOT_AXIS[0],
    ROOT_AXIS[1],
    KNEE_DRIVE_OUTPUT_Z,
)
PROXIMAL_PUSHROD_PIN = (
    ROOT_AXIS[0] + THIGH_NORMAL_X * REMOTE_CRANK_LENGTH,
    ROOT_AXIS[1] + THIGH_NORMAL_Y * REMOTE_CRANK_LENGTH,
    0.0,
)
DISTAL_PUSHROD_PIN = (
    KNEE_AXIS[0] + THIGH_NORMAL_X * DISTAL_CRANK_LENGTH,
    KNEE_AXIS[1] + THIGH_NORMAL_Y * DISTAL_CRANK_LENGTH,
    0.0,
)

# Shared Example 20 external interfaces.  The actuator uses M3 tapped output
# holes; the leg-side plates use ISO-style clearance holes and socket-head
# counterbores at exactly the same centers.
ACTUATOR_OUTPUT_CONNECTOR_Z = ACTUATOR_OUTPUT_FACE_Z
ACTUATOR_CASE_OUTER_RADIUS = ACTUATOR_PACKAGE_RADIUS
OUTPUT_FLANGE_OUTER_RADIUS = 22.4
OUTPUT_FLANGE_REGISTER_INNER_RADIUS = OUTPUT_REGISTER_RADIUS
OUTPUT_FLANGE_BOLT_CIRCLE_RADIUS = OUTPUT_BOLT_CIRCLE_RADIUS
OUTPUT_FLANGE_BOLT_CLEARANCE_RADIUS = 1.65
OUTPUT_FLANGE_BOLT_COUNTERBORE_RADIUS = 3.0
OUTPUT_FLANGE_SCREW_SHANK_RADIUS = 1.5
OUTPUT_FLANGE_BOLT_COUNT = OUTPUT_BOLT_COUNT
OUTPUT_FLANGE_BOLT_ANGLES_DEGREES = OUTPUT_BOLT_ANGLES_DEGREES

CASE_CLAMP_INNER_RADIUS = ACTUATOR_CASE_OUTER_RADIUS + 0.15
CASE_CLAMP_OUTER_RADIUS = 30.5
CASE_CLAMP_WIDTH = 8.0
CASE_CLAMP_SLIT_WIDTH = 2.2
CASE_CLAMP_PINCH_HOLE_RADIUS = 2.15
CASE_CLAMP_BOLT_SHANK_RADIUS = 2.0
CASE_CLAMP_PINCH_AXIS_RADIUS = 32.0
CASE_CLAMP_PINCH_HALF_SPAN = 7.0
THIGH_CASE_CLAMP_Z = ROOT_AXIS[2] - (ACTUATOR_OUTPUT_FACE_Z - ACTUATOR_CASE_CLAMP_Z)
KNEE_CASE_CLAMP_Z = KNEE_DRIVE_OUTPUT_Z - (
    ACTUATOR_OUTPUT_FACE_Z - ACTUATOR_CASE_CLAMP_Z
)
WHEEL_CASE_CLAMP_Z = WHEEL_AXIS[2] - (
    ACTUATOR_OUTPUT_FACE_Z - ACTUATOR_CASE_CLAMP_Z
)

PIN_CLEARANCE_RADIUS = 3.2
ROD_PIN_CLEARANCE_RADIUS = 2.2
LIGHTENING_CORNER_RADIUS = 4.0

UPPER_LINK_Z = 2.5
UPPER_LINK_THICKNESS = 5.0
UPPER_LINK_ROOT_RADIUS = 30.5
UPPER_LINK_KNEE_RADIUS = 17.0
UPPER_LINK_WEB_WIDTH = 28.0
UPPER_LINK_WINDOW_LENGTH = 28.0
UPPER_LINK_WINDOW_WIDTH = 14.0

KNEE_BEARING_OUTER_RADIUS = 14.0
KNEE_BEARING_BORE_RADIUS = 6.0
SHANK_LINK_Z = 10.5
SHANK_LINK_THICKNESS = 5.0
SHANK_KNEE_RADIUS = 18.0
SHANK_WHEEL_RADIUS = 31.5
SHANK_WEB_WIDTH = 24.0
SHANK_WINDOW_LENGTH = 25.0
SHANK_WINDOW_WIDTH = 12.0

REMOTE_CRANK_Z = 88.1
REMOTE_CRANK_THICKNESS = 5.0
REMOTE_CRANK_WIDTH = 12.0
DISTAL_CRANK_Z = 88.1
DISTAL_CRANK_THICKNESS = 5.0
DISTAL_CRANK_WIDTH = 12.0
PUSHROD_Z = 83.1
PUSHROD_THICKNESS = 3.6
PUSHROD_WIDTH = 9.0

WHEEL_TIRE_RADIUS = 48.0
WHEEL_TIRE_WIDTH = 18.0
WHEEL_TIRE_BORE_RADIUS = 34.0
WHEEL_HUB_PLATE_RADIUS = 24.5
WHEEL_HUB_PLATE_THICKNESS = 5.0
WHEEL_SPOKE_WIDTH = 5.5
WHEEL_SPOKE_COUNT = 8

BODY_STANDOFF_Z = 22.0
BODY_STANDOFF_THICKNESS = 8.0
KNEE_STACK_CLAMP_Z = KNEE_CASE_CLAMP_Z
KNEE_STACK_CLAMP_THICKNESS = CASE_CLAMP_WIDTH

assert len(OUTPUT_FLANGE_BOLT_ANGLES_DEGREES) == OUTPUT_FLANGE_BOLT_COUNT
assert OUTPUT_FLANGE_BOLT_CIRCLE_RADIUS == 17.0
assert OUTPUT_FLANGE_REGISTER_INNER_RADIUS == 7.98
assert OUTPUT_REGISTER_HEIGHT == 1.5
assert CASE_CLAMP_INNER_RADIUS > ACTUATOR_CASE_OUTER_RADIUS
assert OUTPUT_FLANGE_BOLT_CIRCLE_RADIUS + OUTPUT_FLANGE_BOLT_COUNTERBORE_RADIUS < 21.0


def validate_leg_interface_dimensions() -> None:
    """Validate shared actuator/leg hole, register, and clamp clearances."""

    generated_angles = tuple(
        OUTPUT_FLANGE_BOLT_ANGLES_DEGREES[0]
        + 360.0 * index / OUTPUT_FLANGE_BOLT_COUNT
        for index in range(OUTPUT_FLANGE_BOLT_COUNT)
    )
    assert generated_angles == OUTPUT_FLANGE_BOLT_ANGLES_DEGREES
    assert OUTPUT_TAP_RADIUS < OUTPUT_FLANGE_SCREW_SHANK_RADIUS
    assert OUTPUT_FLANGE_SCREW_SHANK_RADIUS < OUTPUT_FLANGE_BOLT_CLEARANCE_RADIUS
    assert OUTPUT_FLANGE_BOLT_COUNTERBORE_RADIUS > OUTPUT_FLANGE_SCREW_SHANK_RADIUS
    assert CASE_CLAMP_BOLT_SHANK_RADIUS < CASE_CLAMP_PINCH_HOLE_RADIUS
    assert abs(CASE_CLAMP_INNER_RADIUS - ACTUATOR_CASE_OUTER_RADIUS - 0.15) < 1.0e-9
    print(
        "leg_interface_dimensions: "
        f"output_holes={OUTPUT_FLANGE_BOLT_COUNT} "
        f"pcd={OUTPUT_FLANGE_BOLT_CIRCLE_RADIUS * 2.0:.1f} "
        f"tap_d={OUTPUT_TAP_RADIUS * 2.0:.2f} "
        f"screw_d={OUTPUT_FLANGE_SCREW_SHANK_RADIUS * 2.0:.2f} "
        f"clearance_d={OUTPUT_FLANGE_BOLT_CLEARANCE_RADIUS * 2.0:.2f} "
        f"pilot_d={OUTPUT_FLANGE_REGISTER_INNER_RADIUS * 2.0:.2f}"
    )
